name    'jay-apache_owncloud'
version '0.1.0'
source ''
author 'Jay Steele'
license ''
summary ''
description 'OwnCloud Prerequisites Installation'
project_page ''

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
